In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
import pandas as pd

file_path = "/content/drive/MyDrive/ML -05/w-2/student_data (2).csv"
df = pd.read_csv(file_path)
display(df.head())

   RollNo  Math  Science  English  Gender Department
0       1    55       58       60    Male        CSE
1       2    60       63       64  Female        ECE
2       3    65       68       69    Male        EEE
3       4    70       73       74  Female        CSE
4       5    75       78       80    Male        ECE

In [ ]:
import pandas as pd

file_path = "/content/drive/MyDrive/ML -05/w-2/Titanic-Dataset.csv"
df = pd.read_csv(file_path)
display(df.head())

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S